# Generated by Django 4.2 on 2023-04-15 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('details', models.TextField(blank=True, verbose_name='описание')),
                ('preview_image', models.CharField(blank=True, max_length=256, verbose_name='превью')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('participants', models.ManyToManyField(related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'список задач',
                'verbose_name_plural': 'списки задач',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('content', models.TextField(blank=True, verbose_name='текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todos.todolist', verbose_name='Список дел')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
